import { useState } from 'react';
import { Check, Leaf, SlidersHorizontal } from 'lucide-react';
import Navbar from '../components/Navbar';
import { defaultPreferences, readPreferences, savePreferences } from '../services/preferences';
import type { Preferences as PreferenceValues } from '../types';
const interests = [{ id: 'nature', label: 'Nature', icon: '↟', desc: 'Parks, gardens & open air' }, { id: 'historical', label: 'Historical', icon: '⌂', desc: 'Landmarks & museums' }, { id: 'adventure', label: 'Adventure', icon: '↗', desc: 'Active days out' }, { id: 'family', label: 'Family', icon: '◡', desc: 'Good for all ages' }, { id: 'cultural', label: 'Cultural', icon: '✳', desc: 'Arts & local heritage' }, { id: 'relaxation', label: 'Relaxation', icon: '☼', desc: 'A slower pace' }];
export default function Preferences() {
  const [values, setValues] = useState<PreferenceValues>(readPreferences); const [saved, setSaved] = useState(false);
  const update = (next: Partial<PreferenceValues>) => { setValues((current) => ({ ...current, ...next })); setSaved(false); };
  const save = () => { savePreferences(values); setSaved(true); };
  return <><Navbar/><main className="inner-page preferences-page"><div className="page-heading"><span className="eyebrow">A LITTLE MORE YOU</span><h1>Your travel <em>style.</em></h1><p>Tell us what makes a day out feel like a good one. Your preferences stay on this device.</p></div><div className="preferences-layout"><section className="preference-main">
    <div className="preference-block"><div className="preference-title"><span className="preference-icon"><SlidersHorizontal size={18}/></span><div><span className="eyebrow">01 — THE KIND OF DAY</span><h2>What are you in the mood for?</h2></div></div><div className="interest-grid">{interests.map((item) => <button key={item.id} className={`interest-card ${values.travelType === item.id ? 'selected' : ''}`} onClick={() => update({ travelType: item.id })}><span className="interest-symbol">{item.icon}</span><strong>{item.label}</strong><small>{item.desc}</small>{values.travelType === item.id && <span className="selected-check"><Check size={13}/></span>}</button>)}</div></div>
    <div className="preference-block"><div className="preference-title"><span className="preference-icon"><span>₹</span></span><div><span className="eyebrow">02 — YOUR BUDGET</span><h2>Keep it within reach.</h2></div></div><div className="segmented-control">{['low', 'medium', 'high'].map((budget) => <button key={budget} className={values.budget === budget ? 'active' : ''} onClick={() => update({ budget })}>{budget[0].toUpperCase() + budget.slice(1)}</button>)}</div><p className="field-hint">Budget is saved with your preferences; place pricing is not currently supplied by the live place search.</p></div>
    <div className="preference-block"><div className="preference-title"><span className="preference-icon">↟</span><div><span className="eyebrow">03 — GETTING AROUND</span><h2>How far on foot?</h2></div></div><div className="walking-choice"><button className={!values.walking ? 'active' : ''} onClick={() => update({ walking: false })}><strong>Normal</strong><small>Standard search radius</small></button><button className={values.walking ? 'active' : ''} onClick={() => update({ walking: true })}><strong>Walking preferred</strong><small>Closer places get more weight</small></button></div></div>
    <div className="preference-block"><div className="preference-title"><span className="preference-icon"><Leaf size={18}/></span><div><span className="eyebrow">04 — WHAT MATTERS TO YOU</span><h2>Sustainability preference.</h2></div></div><p className="preference-copy">Set how much sustainability matters in your shortlist. We don’t yet receive verified sustainability data for places, so this preference is saved but cannot change their ranking.</p><div className="range-labels"><span>Not a priority</span><strong>{Math.round(values.sustainabilityPreference * 100)}%</strong><span>Very important</span></div><input className="range-slider" type="range" min="0" max="1" step="0.05" value={values.sustainabilityPreference} onChange={(event) => update({ sustainabilityPreference: Number(event.target.value) })} aria-label="Sustainability preference"/></div>
    <div className="save-row"><button className="button button-primary save-button" onClick={save}>Save preferences <Check size={16}/></button>{saved && <span role="status" className="saved-message">Saved on this device.</span>}</div>
  </section><aside className="preference-aside"><div className="aside-art"><div className="aside-sun"/><div className="aside-hill one"/><div className="aside-hill two"/></div><span className="eyebrow">A NOTE ON THE DATA</span><h3>Thoughtful choices start with honest information.</h3><p>Recommendations use live attraction, distance and weather data. We keep sustainability at a neutral baseline until verified information is available.</p><div className="neutral-chip"><Leaf size={14}/> No unverified green claims</div><button className="reset-link" onClick={() => update(defaultPreferences)}>Reset to defaults</button></aside></div></main><footer className="site-footer inner-footer"><span>© 2026 S-CADE</span><span>Go thoughtfully.</span></footer></>;
}
